### ISSUE TITLE
ListView with notations sends an error and never opens the diary window

### ISSUE THREAD

**Issue by semol18** [SimonFlarup/Sensum-Bosted#11]
Tried to implement the logic from the ListPerson class for the implementation for the ListView for the Map with notations.

Made a new class ListNotation to try the same method with the patient list, but it sends an error after reading the files. The diary window with the list of notations never open.

I first thought that it was because the UUID and Date stood in the wrong order (Date was the key and UUID was the value) in the interface so I tried switching them in the interface, DomainFacade etc. but it didn't seem to work.

**Comment by kvinkel** [comment]
We get an error when calling getNotationsMap().

**Comment by SimonFlarup** [comment]
Fixed with https://github.com/SimonFlarup/Sensum-Bosted/pull/9/commits/141e489b244ef73f992140e7db6b493019276bf6
